apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: avo07bbdf-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/avo07bbdf-java-quarkus-gitops